"""Alembic environment.

The URL always comes from :class:`Settings` so that ``dk db migrate`` and a bare
``alembic upgrade head`` target the same database.
"""

from __future__ import annotations

from logging.config import fileConfig

from alembic import context
from sqlalchemy import pool

from douyin_knowledge.config import get_settings
from douyin_knowledge.db.engine import create_db_engine
from douyin_knowledge.db.models import Base

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name, disable_existing_loggers=False)

target_metadata = Base.metadata


def _url() -> str:
    override = config.get_main_option("sqlalchemy.url_override", None)
    if override:
        return override
    return get_settings().resolved_database_url


def run_migrations_offline() -> None:
    context.configure(
        url=_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        render_as_batch=True,
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    settings = get_settings()
    connectable = config.attributes.get("connection", None)
    if connectable is None:
        engine = create_db_engine(settings)
        with engine.connect() as connection:
            _run(connection)
        engine.dispose()
    else:
        _run(connectable)


def _run(connection: object) -> None:
    context.configure(
        connection=connection,  # type: ignore[arg-type]
        target_metadata=target_metadata,
        # SQLite cannot ALTER most things; batch mode rewrites the table instead.
        render_as_batch=True,
        compare_type=True,
        # search_fts is a virtual table created by raw DDL and must never be
        # autogenerated or dropped.
        include_object=_include_object,
    )
    with context.begin_transaction():
        context.run_migrations()


def _include_object(obj: object, name: str | None, type_: str, *_args: object) -> bool:
    if type_ == "table" and name in {"search_fts", "search_fts_data", "search_fts_idx",
                                    "search_fts_docsize", "search_fts_config"}:
        return False
    return True


_ = pool  # keep the import for parity with the generated template

if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
