"""core schema

All 46 relational tables from docs/PHYSICAL_SCHEMA.md sections 4-50.
The FTS5 virtual table and partial indexes are created in 0002.

Revision ID: 0001_core_schema
Revises: none (this is the base revision)
Create Date: 2026-09-18 01:24:18.013298
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001_core_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value_json', sa.JSON().with_variant(sa.JSON(none_as_null=True), 'sqlite'), nullable=False),
    sa.Column('updated_at_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_app_settings'))
    )
    op.create_table('collections',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('external_collection_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.JSON().with_variant(sa.JSON(none_as_null=True), 'sqlite'), nullable=True),
    sa.Column('first_seen_at_ms', sa.Integer(), nullable=False),
    sa.Column('last_synced_at_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collections')),
    sa.UniqueConstraint('platform', 'external_collection_id', name='uq_collections_platform_external')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.Column('updated_at_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index('ix_conversations_updated_at_ms', ['updated_at_ms'], unique=False)

    op.create_table('creators',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('external_creator_id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('handle', sa.Text(), nullable=True),
    sa.Column('profile_url', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('raw_json', sa.JSON().with_variant(sa.JSON(none_as_null=True), 'sqlite'), nullable=True),
    sa.Column('first_seen_at_ms', sa.Integer(), nullable=False),
    sa.Column('last_seen_at_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_creators')),
    sa.UniqueConstraint('platform', 'external_creator_id', name='uq_creators_platform_external')
    )
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.create_index('ix_creators_handle', ['handle'], unique=False)
        batch_op.create_index('ix_creators_platform_display_name', ['platform', 'display_name'], unique=False)

    op.create_table('entities',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('subtype', sa.Text(), nullable=True),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('normalized_name', sa.Text(), nullable=False),
    sa.Column('profile_json', sa.JSON().with_variant(sa.JSON(none_as_null=True), 'sqlite'), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('merged_into_entity_id', sa.Text(), nullable=True),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.Column('updated_at_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['merged_into_entity_id'], ['entities.id'], name=op.f('fk_entities_merged_into_entity_id_entities'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entities'))
    )
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index('ix_entities_status', ['status'], unique=False)
        batch_op.create_index('ix_entities_type_normalized_name', ['entity_type', 'normalized_name'], unique=False)

    op.create_table('quality_rules',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('rule_key', sa.Text(), nullable=False),
    sa.Column('finding_type', sa.Text(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('pass_count', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('last_triggered_at_ms', sa.Integer(), nullable=True),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.Column('updated_at_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quality_rules')),
    sa.UniqueConstraint('rule_key', name='uq_quality_rules_rule_key')
    )
    with op.batch_alter_table('quality_rules', schema=None) as batch_op:
        batch_op.create_index('ix_quality_rules_status_finding_type', ['status', 'finding_type'], unique=False)

    op.create_table('search_documents',
    sa.Column('rowid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('doc_type', sa.Text(), nullable=False),
    sa.Column('object_id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON().with_variant(sa.JSON(none_as_null=True), 'sqlite'), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('updated_at_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('rowid', name=op.f('pk_search_documents')),
    sa.UniqueConstraint('doc_type', 'object_id', name='uq_search_documents_doc_type_object_id'),
    sa.UniqueConstraint('id', name=op.f('uq_search_documents_id'))
    )
    with op.batch_alter_table('search_documents', schema=None) as batch_op:
        batch_op.create_index('ix_search_documents_updated_at_ms', ['updated_at_ms'], unique=False)

    op.create_table('topics',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('normalized_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.Column('updated_at_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics')),
    sa.UniqueConstraint('normalized_name', name='uq_topics_normalized_name')
    )
    op.create_table('vector_documents',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('doc_type', sa.Text(), nullable=False),
    sa.Column('object_id', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('embedding_model', sa.Text(), nullable=False),
    sa.Column('embedding_dim', sa.Integer(), nullable=False),
    sa.Column('vector_key', sa.Text(), nullable=False),
    sa.Column('indexed_at_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vector_documents')),
    sa.UniqueConstraint('doc_type', 'object_id', 'embedding_model', name='uq_vector_documents_identity')
    )
    with op.batch_alter_table('vector_documents', schema=None) as batch_op:
        batch_op.create_index('ix_vector_documents_vector_key', ['vector_key'], unique=False)

    op.create_table('conversation_state',
    sa.Column('conversation_id', sa.Text(), nullable=False),
    sa.Column('state_json', sa.JSON().with_variant(sa.JSON(none_as_null=True), 'sqlite'), nullable=False),
    sa.Column('updated_at_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_conversation_state_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id', name=op.f('pk_conversation_state'))
    )
    op.create_table('entity_aliases',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('alias', sa.Text(), nullable=False),
    sa.Column('normalized_alias', sa.Text(), nullable=False),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('origin', sa.Text(), nullable=False),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_entity_aliases_entity_id_entities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_aliases')),
    sa.UniqueConstraint('entity_id', 'normalized_alias', name='uq_entity_aliases_entity_alias')
    )
    with op.batch_alter_table('entity_aliases', schema=None) as batch_op:
        batch_op.create_index('ix_entity_aliases_normalized_alias', ['normalized_alias'], unique=False)

    op.create_table('entity_external_ids',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('namespace', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_entity_external_ids_entity_id_entities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_external_ids')),
    sa.UniqueConstraint('namespace', 'value', name='uq_entity_external_ids_namespace_value')
    )
    with op.batch_alter_table('entity_external_ids', schema=None) as batch_op:
        batch_op.create_index('ix_entity_external_ids_entity_id', ['entity_id'], unique=False)

    op.create_table('entity_user_states',
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('attributes_json', sa.JSON().with_variant(sa.JSON(none_as_null=True), 'sqlite'), nullable=True),
    sa.Column('first_action_at_ms', sa.Integer(), nullable=True),
    sa.Column('last_action_at_ms', sa.Integer(), nullable=True),
    sa.Column('updated_at_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_entity_user_states_entity_id_entities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_id', name=op.f('pk_entity_user_states'))
    )
    with op.batch_alter_table('entity_user_states', schema=None) as batch_op:
        batch_op.create_index('ix_entity_user_states_state', ['state'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('conversation_id', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('knowledge_scope', sa.Text(), nullable=True),
    sa.Column('query_plan_json', sa.JSON().with_variant(sa.JSON(none_as_null=True), 'sqlite'), nullable=True),
    sa.Column('response_meta_json', sa.JSON().with_variant(sa.JSON(none_as_null=True), 'sqlite'), nullable=True),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_messages_conversation_created', ['conversation_id', 'created_at_ms'], unique=False)

    op.create_table('sources',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('creator_id', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('caption_raw', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('cover_url', sa.Text(), nullable=True),
    sa.Column('published_at_ms', sa.Integer(), nullable=True),
    sa.Column('saved_at_ms', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('availability', sa.Text(), nullable=False),
    sa.Column('latest_snapshot_id', sa.Text(), nullable=True),
    sa.Column('first_seen_at_ms', sa.Integer(), nullable=False),
    sa.Column('last_seen_at_ms', sa.Integer(), nullable=False),
    sa.Column('locally_deleted_at_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], name=op.f('fk_sources_creator_id_creators')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('platform', 'external_id', name='uq_sources_platform_external_id')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index('ix_sources_creator_id', ['creator_id'], unique=False)
        batch_op.create_index('ix_sources_saved_at_ms', ['saved_at_ms'], unique=False)
        batch_op.create_index('ix_sources_source_type', ['source_type'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('job_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.JSON().with_variant(sa.JSON(none_as_null=True), 'sqlite'), nullable=True),
    sa.Column('dedupe_key', sa.Text(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('available_at_ms', sa.Integer(), nullable=False),
    sa.Column('locked_at_ms', sa.Integer(), nullable=True),
    sa.Column('locked_by', sa.Text(), nullable=True),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.Column('started_at_ms', sa.Integer(), nullable=True),
    sa.Column('finished_at_ms', sa.Integer(), nullable=True),
    sa.Column('last_error_json', sa.JSON().with_variant(sa.JSON(none_as_null=True), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_jobs_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('dedupe_key', name='uq_jobs_dedupe_key')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_locked_at_ms', ['locked_at_ms'], unique=False)
        batch_op.create_index('ix_jobs_source_id', ['source_id'], unique=False)
        batch_op.create_index('ix_jobs_status_priority_available', ['status', 'priority', 'available_at_ms'], unique=False)
        batch_op.create_index('ix_jobs_type_status', ['job_type', 'status'], unique=False)

    op.create_table('processing_rules',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('target_source_id', sa.Text(), nullable=True),
    sa.Column('target_creator_id', sa.Text(), nullable=True),
    sa.Column('target_collection_id', sa.Text(), nullable=True),
    sa.Column('matcher_json', sa.JSON().with_variant(sa.JSON(none_as_null=True), 'sqlite'), nullable=True),
    sa.Column('origin', sa.Text(), nullable=False),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.Column('updated_at_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['target_collection_id'], ['collections.id'], name=op.f('fk_processing_rules_target_collection_id_collections')),
    sa.ForeignKeyConstraint(['target_creator_id'], ['creators.id'], name=op.f('fk_processing_rules_target_creator_id_creators')),
    sa.ForeignKeyConstraint(['target_source_id'], ['sources.id'], name=op.f('fk_processing_rules_target_source_id_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_rules'))
    )
    with op.batch_alter_table('processing_rules', schema=None) as batch_op:
        batch_op.create_index('ix_processing_rules_enabled_type', ['is_enabled', 'rule_type'], unique=False)
        batch_op.create_index('ix_processing_rules_target_collection_id', ['target_collection_id'], unique=False)
        batch_op.create_index('ix_processing_rules_target_creator_id', ['target_creator_id'], unique=False)
        batch_op.create_index('ix_processing_rules_target_source_id', ['target_source_id'], unique=False)

    op.create_table('processing_runs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('run_kind', sa.Text(), nullable=False),
    sa.Column('processor_version', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Text(), nullable=False),
    sa.Column('target_level', sa.Integer(), nullable=False),
    sa.Column('achieved_level', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('models_json', sa.JSON().with_variant(sa.JSON(none_as_null=True), 'sqlite'), nullable=True),
    sa.Column('config_json', sa.JSON().with_variant(sa.JSON(none_as_null=True), 'sqlite'), nullable=True),
    sa.Column('started_at_ms', sa.Integer(), nullable=False),
    sa.Column('finished_at_ms', sa.Integer(), nullable=True),
    sa.Column('error_json', sa.JSON().with_variant(sa.JSON(none_as_null=True), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_processing_runs_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_runs'))
    )
    with op.batch_alter_table('processing_runs', schema=None) as batch_op:
        batch_op.create_index('ix_processing_runs_source_started', ['source_id', 'started_at_ms'], unique=False)
        batch_op.create_index('ix_processing_runs_status', ['status'], unique=False)

    op.create_table('source_assets',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('asset_type', sa.Text(), nullable=False),
    sa.Column('retention_class', sa.Text(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.Text(), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('timestamp_ms', sa.Integer(), nullable=True),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.Column('expires_at_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_source_assets_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_assets'))
    )
    with op.batch_alter_table('source_assets', schema=None) as batch_op:
        batch_op.create_index('ix_source_assets_retention_expires', ['retention_class', 'expires_at_ms'], unique=False)
        batch_op.create_index('ix_source_assets_source_type', ['source_id', 'asset_type'], unique=False)

    op.create_table('source_collection_memberships',
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('collection_id', sa.Text(), nullable=False),
    sa.Column('first_seen_at_ms', sa.Integer(), nullable=False),
    sa.Column('last_seen_at_ms', sa.Integer(), nullable=False),
    sa.Column('is_present', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name=op.f('fk_source_collection_memberships_collection_id_collections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_source_collection_memberships_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id', 'collection_id', name=op.f('pk_source_collection_memberships'))
    )
    op.create_table('source_snapshots',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('fetched_at_ms', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('raw_json', sa.JSON().with_variant(sa.JSON(none_as_null=True), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_source_snapshots_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_snapshots'))
    )
    with op.batch_alter_table('source_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_source_snapshots_source_fetched', ['source_id', 'fetched_at_ms'], unique=False)
        batch_op.create_index('ix_source_snapshots_source_hash', ['source_id', 'content_hash'], unique=False)

    op.create_table('wiki_pages',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('page_type', sa.Text(), nullable=False),
    sa.Column('canonical_key', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=True),
    sa.Column('topic_id', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.Column('updated_at_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_wiki_pages_entity_id_entities'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_wiki_pages_source_id_sources'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_wiki_pages_topic_id_topics'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wiki_pages')),
    sa.UniqueConstraint('canonical_key', name='uq_wiki_pages_canonical_key')
    )
    with op.batch_alter_table('wiki_pages', schema=None) as batch_op:
        batch_op.create_index('ix_wiki_pages_entity_id', ['entity_id'], unique=False)
        batch_op.create_index('ix_wiki_pages_page_type_status', ['page_type', 'status'], unique=False)
        batch_op.create_index('ix_wiki_pages_slug', ['slug'], unique=False)
        batch_op.create_index('ix_wiki_pages_topic_id', ['topic_id'], unique=False)

    op.create_table('claims',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('processing_run_id', sa.Text(), nullable=False),
    sa.Column('subject_entity_id', sa.Text(), nullable=True),
    sa.Column('subject_topic_id', sa.Text(), nullable=True),
    sa.Column('subject_text', sa.Text(), nullable=True),
    sa.Column('predicate', sa.Text(), nullable=False),
    sa.Column('object_entity_id', sa.Text(), nullable=True),
    sa.Column('object_topic_id', sa.Text(), nullable=True),
    sa.Column('value_type', sa.Text(), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_number', sa.Float(), nullable=True),
    sa.Column('value_json', sa.JSON().with_variant(sa.JSON(none_as_null=True), 'sqlite'), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('claim_kind', sa.Text(), nullable=False),
    sa.Column('provenance_type', sa.Text(), nullable=False),
    sa.Column('attribution', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('valid_from_ms', sa.Integer(), nullable=True),
    sa.Column('valid_to_ms', sa.Integer(), nullable=True),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.CheckConstraint('subject_entity_id IS NOT NULL OR subject_topic_id IS NOT NULL OR subject_text IS NOT NULL', name=op.f('ck_claims_claims_subject_present')),
    sa.ForeignKeyConstraint(['object_entity_id'], ['entities.id'], name=op.f('fk_claims_object_entity_id_entities'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['object_topic_id'], ['topics.id'], name=op.f('fk_claims_object_topic_id_topics'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['processing_run_id'], ['processing_runs.id'], name=op.f('fk_claims_processing_run_id_processing_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_claims_source_id_sources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_entity_id'], ['entities.id'], name=op.f('fk_claims_subject_entity_id_entities'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_topic_id'], ['topics.id'], name=op.f('fk_claims_subject_topic_id_topics'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims'))
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index('ix_claims_predicate', ['predicate'], unique=False)
        batch_op.create_index('ix_claims_processing_run_id', ['processing_run_id'], unique=False)
        batch_op.create_index('ix_claims_source_id', ['source_id'], unique=False)
        batch_op.create_index('ix_claims_subject_entity_predicate', ['subject_entity_id', 'predicate'], unique=False)
        batch_op.create_index('ix_claims_subject_topic_predicate', ['subject_topic_id', 'predicate'], unique=False)

    op.create_table('entity_mentions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('processing_run_id', sa.Text(), nullable=False),
    sa.Column('mention_text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=False),
    sa.Column('entity_type_hint', sa.Text(), nullable=True),
    sa.Column('context_json', sa.JSON().with_variant(sa.JSON(none_as_null=True), 'sqlite'), nullable=True),
    sa.Column('resolved_entity_id', sa.Text(), nullable=True),
    sa.Column('resolution_status', sa.Text(), nullable=False),
    sa.Column('resolution_confidence', sa.Float(), nullable=True),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['processing_run_id'], ['processing_runs.id'], name=op.f('fk_entity_mentions_processing_run_id_processing_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_entity_id'], ['entities.id'], name=op.f('fk_entity_mentions_resolved_entity_id_entities'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_entity_mentions_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_mentions'))
    )
    with op.batch_alter_table('entity_mentions', schema=None) as batch_op:
        batch_op.create_index('ix_entity_mentions_normalized_text', ['normalized_text'], unique=False)
        batch_op.create_index('ix_entity_mentions_resolution_status', ['resolution_status'], unique=False)
        batch_op.create_index('ix_entity_mentions_resolved_entity_id', ['resolved_entity_id'], unique=False)
        batch_op.create_index('ix_entity_mentions_source_run', ['source_id', 'processing_run_id'], unique=False)

    op.create_table('evidence_units',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('asset_id', sa.Text(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=True),
    sa.Column('end_ms', sa.Integer(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('normalized_text', sa.Text(), nullable=True),
    sa.Column('observation_json', sa.JSON().with_variant(sa.JSON(none_as_null=True), 'sqlite'), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['source_assets.id'], name=op.f('fk_evidence_units_asset_id_source_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_evidence_units_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_units')),
    sa.UniqueConstraint('source_id', 'kind', 'content_hash', name='uq_evidence_source_kind_hash')
    )
    with op.batch_alter_table('evidence_units', schema=None) as batch_op:
        batch_op.create_index('ix_evidence_units_content_hash', ['content_hash'], unique=False)
        batch_op.create_index('ix_evidence_units_source_kind', ['source_id', 'kind'], unique=False)

    op.create_table('job_events',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('job_id', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('data_json', sa.JSON().with_variant(sa.JSON(none_as_null=True), 'sqlite'), nullable=True),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_events_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_events'))
    )
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.create_index('ix_job_events_job_created', ['job_id', 'created_at_ms'], unique=False)

    op.create_table('knowledge_items',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('processing_run_id', sa.Text(), nullable=False),
    sa.Column('generated_title', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_points_json', sa.JSON().with_variant(sa.JSON(none_as_null=True), 'sqlite'), nullable=True),
    sa.Column('processing_level', sa.Integer(), nullable=False),
    sa.Column('coverage_json', sa.JSON().with_variant(sa.JSON(none_as_null=True), 'sqlite'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['processing_run_id'], ['processing_runs.id'], name=op.f('fk_knowledge_items_processing_run_id_processing_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_knowledge_items_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_items')),
    sa.UniqueConstraint('processing_run_id', name='uq_knowledge_items_processing_run_id')
    )
    with op.batch_alter_table('knowledge_items', schema=None) as batch_op:
        batch_op.create_index('ix_knowledge_items_source_id', ['source_id'], unique=False)

    op.create_table('policy_decisions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('rule_id', sa.Text(), nullable=True),
    sa.Column('phase', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('reason_code', sa.Text(), nullable=True),
    sa.Column('explanation_json', sa.JSON().with_variant(sa.JSON(none_as_null=True), 'sqlite'), nullable=True),
    sa.Column('model_name', sa.Text(), nullable=True),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['processing_rules.id'], name=op.f('fk_policy_decisions_rule_id_processing_rules'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_policy_decisions_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_decisions'))
    )
    with op.batch_alter_table('policy_decisions', schema=None) as batch_op:
        batch_op.create_index('ix_policy_decisions_source_created', ['source_id', 'created_at_ms'], unique=False)

    op.create_table('retrieval_chunks',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('processing_run_id', sa.Text(), nullable=False),
    sa.Column('chunk_type', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=True),
    sa.Column('end_ms', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['processing_run_id'], ['processing_runs.id'], name=op.f('fk_retrieval_chunks_processing_run_id_processing_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_retrieval_chunks_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retrieval_chunks')),
    sa.UniqueConstraint('processing_run_id', 'chunk_type', 'ordinal', name='uq_retrieval_chunk_run_type_ordinal')
    )
    with op.batch_alter_table('retrieval_chunks', schema=None) as batch_op:
        batch_op.create_index('ix_retrieval_chunks_run_id', ['processing_run_id'], unique=False)
        batch_op.create_index('ix_retrieval_chunks_source_id', ['source_id'], unique=False)

    op.create_table('wiki_integration_runs',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('trigger_type', sa.Text(), nullable=False),
    sa.Column('trigger_source_id', sa.Text(), nullable=True),
    sa.Column('processing_run_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('selected_pages_json', sa.JSON().with_variant(sa.JSON(none_as_null=True), 'sqlite'), nullable=True),
    sa.Column('model_name', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.Text(), nullable=True),
    sa.Column('context_stats_json', sa.JSON().with_variant(sa.JSON(none_as_null=True), 'sqlite'), nullable=True),
    sa.Column('started_at_ms', sa.Integer(), nullable=False),
    sa.Column('finished_at_ms', sa.Integer(), nullable=True),
    sa.Column('error_json', sa.JSON().with_variant(sa.JSON(none_as_null=True), 'sqlite'), nullable=True),
    sa.ForeignKeyConstraint(['processing_run_id'], ['processing_runs.id'], name=op.f('fk_wiki_integration_runs_processing_run_id_processing_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trigger_source_id'], ['sources.id'], name=op.f('fk_wiki_integration_runs_trigger_source_id_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wiki_integration_runs'))
    )
    with op.batch_alter_table('wiki_integration_runs', schema=None) as batch_op:
        batch_op.create_index('ix_wiki_integration_runs_started', ['started_at_ms'], unique=False)

    op.create_table('claim_evidence',
    sa.Column('claim_id', sa.Text(), nullable=False),
    sa.Column('evidence_id', sa.Text(), nullable=False),
    sa.Column('support_role', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_claim_evidence_claim_id_claims'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_units.id'], name=op.f('fk_claim_evidence_evidence_id_evidence_units'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('claim_id', 'evidence_id', 'support_role', name=op.f('pk_claim_evidence'))
    )
    op.create_table('entity_mention_evidence',
    sa.Column('entity_mention_id', sa.Text(), nullable=False),
    sa.Column('evidence_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['entity_mention_id'], ['entity_mentions.id'], name=op.f('fk_entity_mention_evidence_entity_mention_id_entity_mentions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_units.id'], name=op.f('fk_entity_mention_evidence_evidence_id_evidence_units'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entity_mention_id', 'evidence_id', name=op.f('pk_entity_mention_evidence'))
    )
    op.create_table('knowledge_item_labels',
    sa.Column('knowledge_item_id', sa.Text(), nullable=False),
    sa.Column('label_type', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_item_id'], ['knowledge_items.id'], name=op.f('fk_knowledge_item_labels_knowledge_item_id_knowledge_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('knowledge_item_id', 'label_type', 'value', name=op.f('pk_knowledge_item_labels'))
    )
    with op.batch_alter_table('knowledge_item_labels', schema=None) as batch_op:
        batch_op.create_index('ix_knowledge_item_labels_type_value', ['label_type', 'value'], unique=False)

    op.create_table('knowledge_item_topics',
    sa.Column('knowledge_item_id', sa.Text(), nullable=False),
    sa.Column('topic_id', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_item_id'], ['knowledge_items.id'], name=op.f('fk_knowledge_item_topics_knowledge_item_id_knowledge_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_knowledge_item_topics_topic_id_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('knowledge_item_id', 'topic_id', name=op.f('pk_knowledge_item_topics'))
    )
    op.create_table('knowledge_item_user_states',
    sa.Column('knowledge_item_id', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('attributes_json', sa.JSON().with_variant(sa.JSON(none_as_null=True), 'sqlite'), nullable=True),
    sa.Column('updated_at_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_item_id'], ['knowledge_items.id'], name=op.f('fk_knowledge_item_user_states_knowledge_item_id_knowledge_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('knowledge_item_id', name=op.f('pk_knowledge_item_user_states'))
    )
    op.create_table('message_citations',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('message_id', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=True),
    sa.Column('evidence_id', sa.Text(), nullable=True),
    sa.Column('claim_id', sa.Text(), nullable=True),
    sa.Column('wiki_page_id', sa.Text(), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.CheckConstraint('source_id IS NOT NULL OR evidence_id IS NOT NULL OR claim_id IS NOT NULL OR wiki_page_id IS NOT NULL', name=op.f('ck_message_citations_message_citations_target_present')),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_message_citations_claim_id_claims'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_units.id'], name=op.f('fk_message_citations_evidence_id_evidence_units'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_message_citations_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_message_citations_source_id_sources'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wiki_page_id'], ['wiki_pages.id'], name=op.f('fk_message_citations_wiki_page_id_wiki_pages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_citations'))
    )
    with op.batch_alter_table('message_citations', schema=None) as batch_op:
        batch_op.create_index('ix_message_citations_message_ordinal', ['message_id', 'ordinal'], unique=False)

    op.create_table('processing_run_evidence',
    sa.Column('processing_run_id', sa.Text(), nullable=False),
    sa.Column('evidence_id', sa.Text(), nullable=False),
    sa.Column('usage_role', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_units.id'], name=op.f('fk_processing_run_evidence_evidence_id_evidence_units'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processing_run_id'], ['processing_runs.id'], name=op.f('fk_processing_run_evidence_processing_run_id_processing_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('processing_run_id', 'evidence_id', name=op.f('pk_processing_run_evidence'))
    )
    op.create_table('retrieval_chunk_evidence',
    sa.Column('retrieval_chunk_id', sa.Text(), nullable=False),
    sa.Column('evidence_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_units.id'], name=op.f('fk_retrieval_chunk_evidence_evidence_id_evidence_units'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retrieval_chunk_id'], ['retrieval_chunks.id'], name=op.f('fk_retrieval_chunk_evidence_retrieval_chunk_id_retrieval_chunks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('retrieval_chunk_id', 'evidence_id', name=op.f('pk_retrieval_chunk_evidence'))
    )
    op.create_table('source_processing_state',
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('current_policy_action', sa.Text(), nullable=False),
    sa.Column('current_policy_decision_id', sa.Text(), nullable=True),
    sa.Column('processing_status', sa.Text(), nullable=False),
    sa.Column('desired_level', sa.Integer(), nullable=False),
    sa.Column('achieved_level', sa.Integer(), nullable=False),
    sa.Column('current_processing_run_id', sa.Text(), nullable=True),
    sa.Column('last_success_at_ms', sa.Integer(), nullable=True),
    sa.Column('last_error_json', sa.JSON().with_variant(sa.JSON(none_as_null=True), 'sqlite'), nullable=True),
    sa.Column('updated_at_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['current_policy_decision_id'], ['policy_decisions.id'], name=op.f('fk_source_processing_state_current_policy_decision_id_policy_decisions')),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_source_processing_state_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id', name=op.f('pk_source_processing_state'))
    )
    with op.batch_alter_table('source_processing_state', schema=None) as batch_op:
        batch_op.create_index('ix_source_processing_state_policy_action', ['current_policy_action'], unique=False)
        batch_op.create_index('ix_source_processing_state_status', ['processing_status'], unique=False)

    op.create_table('user_annotations',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=True),
    sa.Column('entity_id', sa.Text(), nullable=True),
    sa.Column('knowledge_item_id', sa.Text(), nullable=True),
    sa.Column('annotation_type', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('value_json', sa.JSON().with_variant(sa.JSON(none_as_null=True), 'sqlite'), nullable=True),
    sa.Column('occurred_at_ms', sa.Integer(), nullable=True),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.CheckConstraint('source_id IS NOT NULL OR entity_id IS NOT NULL OR knowledge_item_id IS NOT NULL', name=op.f('ck_user_annotations_user_annotations_target_present')),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_user_annotations_entity_id_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_item_id'], ['knowledge_items.id'], name=op.f('fk_user_annotations_knowledge_item_id_knowledge_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_user_annotations_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_annotations'))
    )
    with op.batch_alter_table('user_annotations', schema=None) as batch_op:
        batch_op.create_index('ix_user_annotations_entity_id', ['entity_id'], unique=False)
        batch_op.create_index('ix_user_annotations_source_id', ['source_id'], unique=False)
        batch_op.create_index('ix_user_annotations_type_created', ['annotation_type', 'created_at_ms'], unique=False)

    op.create_table('wiki_revisions',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('page_id', sa.Text(), nullable=False),
    sa.Column('integration_run_id', sa.Text(), nullable=True),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('mutation_type', sa.Text(), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('frontmatter_json', sa.JSON().with_variant(sa.JSON(none_as_null=True), 'sqlite'), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('is_current', sa.Integer(), nullable=False),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['integration_run_id'], ['wiki_integration_runs.id'], name=op.f('fk_wiki_revisions_integration_run_id_wiki_integration_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['page_id'], ['wiki_pages.id'], name=op.f('fk_wiki_revisions_page_id_wiki_pages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wiki_revisions')),
    sa.UniqueConstraint('page_id', 'revision_no', name='uq_wiki_revisions_page_revision_no')
    )
    with op.batch_alter_table('wiki_revisions', schema=None) as batch_op:
        batch_op.create_index('ix_wiki_revisions_page_current', ['page_id', 'is_current'], unique=False)

    op.create_table('wiki_links',
    sa.Column('from_page_id', sa.Text(), nullable=False),
    sa.Column('to_page_id', sa.Text(), nullable=False),
    sa.Column('link_type', sa.Text(), nullable=False),
    sa.Column('source_revision_id', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['from_page_id'], ['wiki_pages.id'], name=op.f('fk_wiki_links_from_page_id_wiki_pages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_revision_id'], ['wiki_revisions.id'], name=op.f('fk_wiki_links_source_revision_id_wiki_revisions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_page_id'], ['wiki_pages.id'], name=op.f('fk_wiki_links_to_page_id_wiki_pages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('from_page_id', 'to_page_id', 'link_type', 'source_revision_id', name=op.f('pk_wiki_links'))
    )
    with op.batch_alter_table('wiki_links', schema=None) as batch_op:
        batch_op.create_index('ix_wiki_links_to_page_id', ['to_page_id'], unique=False)

    op.create_table('wiki_lint_findings',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('page_id', sa.Text(), nullable=True),
    sa.Column('revision_id', sa.Text(), nullable=True),
    sa.Column('finding_type', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('details_json', sa.JSON().with_variant(sa.JSON(none_as_null=True), 'sqlite'), nullable=False),
    sa.Column('detected_at_ms', sa.Integer(), nullable=False),
    sa.Column('resolved_at_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['wiki_pages.id'], name=op.f('fk_wiki_lint_findings_page_id_wiki_pages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revision_id'], ['wiki_revisions.id'], name=op.f('fk_wiki_lint_findings_revision_id_wiki_revisions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wiki_lint_findings'))
    )
    with op.batch_alter_table('wiki_lint_findings', schema=None) as batch_op:
        batch_op.create_index('ix_wiki_lint_findings_page_id', ['page_id'], unique=False)
        batch_op.create_index('ix_wiki_lint_findings_status_type', ['status', 'finding_type'], unique=False)

    op.create_table('wiki_supports',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('wiki_revision_id', sa.Text(), nullable=False),
    sa.Column('statement_key', sa.Text(), nullable=False),
    sa.Column('claim_id', sa.Text(), nullable=True),
    sa.Column('evidence_id', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Text(), nullable=True),
    sa.Column('support_role', sa.Text(), nullable=False),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.CheckConstraint('claim_id IS NOT NULL OR evidence_id IS NOT NULL OR source_id IS NOT NULL', name=op.f('ck_wiki_supports_wiki_supports_target_present')),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_wiki_supports_claim_id_claims'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence_units.id'], name=op.f('fk_wiki_supports_evidence_id_evidence_units'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_wiki_supports_source_id_sources'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wiki_revision_id'], ['wiki_revisions.id'], name=op.f('fk_wiki_supports_wiki_revision_id_wiki_revisions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wiki_supports'))
    )
    with op.batch_alter_table('wiki_supports', schema=None) as batch_op:
        batch_op.create_index('ix_wiki_supports_claim_id', ['claim_id'], unique=False)
        batch_op.create_index('ix_wiki_supports_revision_statement', ['wiki_revision_id', 'statement_key'], unique=False)
        batch_op.create_index('ix_wiki_supports_source_id', ['source_id'], unique=False)

    op.create_table('quality_ledger',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('finding_id', sa.Text(), nullable=True),
    sa.Column('quality_rule_id', sa.Text(), nullable=True),
    sa.Column('action_type', sa.Text(), nullable=False),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('before_json', sa.JSON().with_variant(sa.JSON(none_as_null=True), 'sqlite'), nullable=True),
    sa.Column('after_json', sa.JSON().with_variant(sa.JSON(none_as_null=True), 'sqlite'), nullable=True),
    sa.Column('model_name', sa.Text(), nullable=True),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['wiki_lint_findings.id'], name=op.f('fk_quality_ledger_finding_id_wiki_lint_findings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quality_rule_id'], ['quality_rules.id'], name=op.f('fk_quality_ledger_quality_rule_id_quality_rules'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quality_ledger'))
    )
    with op.batch_alter_table('quality_ledger', schema=None) as batch_op:
        batch_op.create_index('ix_quality_ledger_created_action', ['created_at_ms', 'action_type'], unique=False)

    op.create_table('quality_rule_samples',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('quality_rule_id', sa.Text(), nullable=False),
    sa.Column('finding_id', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Text(), nullable=True),
    sa.Column('wiki_page_id', sa.Text(), nullable=True),
    sa.Column('context_json', sa.JSON().with_variant(sa.JSON(none_as_null=True), 'sqlite'), nullable=True),
    sa.Column('is_fixed', sa.Integer(), nullable=False),
    sa.Column('created_at_ms', sa.Integer(), nullable=False),
    sa.Column('fixed_at_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['finding_id'], ['wiki_lint_findings.id'], name=op.f('fk_quality_rule_samples_finding_id_wiki_lint_findings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quality_rule_id'], ['quality_rules.id'], name=op.f('fk_quality_rule_samples_quality_rule_id_quality_rules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_quality_rule_samples_source_id_sources'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wiki_page_id'], ['wiki_pages.id'], name=op.f('fk_quality_rule_samples_wiki_page_id_wiki_pages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quality_rule_samples'))
    )
    with op.batch_alter_table('quality_rule_samples', schema=None) as batch_op:
        batch_op.create_index('ix_quality_rule_samples_rule_fixed', ['quality_rule_id', 'is_fixed'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quality_rule_samples', schema=None) as batch_op:
        batch_op.drop_index('ix_quality_rule_samples_rule_fixed')

    op.drop_table('quality_rule_samples')
    with op.batch_alter_table('quality_ledger', schema=None) as batch_op:
        batch_op.drop_index('ix_quality_ledger_created_action')

    op.drop_table('quality_ledger')
    with op.batch_alter_table('wiki_supports', schema=None) as batch_op:
        batch_op.drop_index('ix_wiki_supports_source_id')
        batch_op.drop_index('ix_wiki_supports_revision_statement')
        batch_op.drop_index('ix_wiki_supports_claim_id')

    op.drop_table('wiki_supports')
    with op.batch_alter_table('wiki_lint_findings', schema=None) as batch_op:
        batch_op.drop_index('ix_wiki_lint_findings_status_type')
        batch_op.drop_index('ix_wiki_lint_findings_page_id')

    op.drop_table('wiki_lint_findings')
    with op.batch_alter_table('wiki_links', schema=None) as batch_op:
        batch_op.drop_index('ix_wiki_links_to_page_id')

    op.drop_table('wiki_links')
    with op.batch_alter_table('wiki_revisions', schema=None) as batch_op:
        batch_op.drop_index('ix_wiki_revisions_page_current')

    op.drop_table('wiki_revisions')
    with op.batch_alter_table('user_annotations', schema=None) as batch_op:
        batch_op.drop_index('ix_user_annotations_type_created')
        batch_op.drop_index('ix_user_annotations_source_id')
        batch_op.drop_index('ix_user_annotations_entity_id')

    op.drop_table('user_annotations')
    with op.batch_alter_table('source_processing_state', schema=None) as batch_op:
        batch_op.drop_index('ix_source_processing_state_status')
        batch_op.drop_index('ix_source_processing_state_policy_action')

    op.drop_table('source_processing_state')
    op.drop_table('retrieval_chunk_evidence')
    op.drop_table('processing_run_evidence')
    with op.batch_alter_table('message_citations', schema=None) as batch_op:
        batch_op.drop_index('ix_message_citations_message_ordinal')

    op.drop_table('message_citations')
    op.drop_table('knowledge_item_user_states')
    op.drop_table('knowledge_item_topics')
    with op.batch_alter_table('knowledge_item_labels', schema=None) as batch_op:
        batch_op.drop_index('ix_knowledge_item_labels_type_value')

    op.drop_table('knowledge_item_labels')
    op.drop_table('entity_mention_evidence')
    op.drop_table('claim_evidence')
    with op.batch_alter_table('wiki_integration_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_wiki_integration_runs_started')

    op.drop_table('wiki_integration_runs')
    with op.batch_alter_table('retrieval_chunks', schema=None) as batch_op:
        batch_op.drop_index('ix_retrieval_chunks_source_id')
        batch_op.drop_index('ix_retrieval_chunks_run_id')

    op.drop_table('retrieval_chunks')
    with op.batch_alter_table('policy_decisions', schema=None) as batch_op:
        batch_op.drop_index('ix_policy_decisions_source_created')

    op.drop_table('policy_decisions')
    with op.batch_alter_table('knowledge_items', schema=None) as batch_op:
        batch_op.drop_index('ix_knowledge_items_source_id')

    op.drop_table('knowledge_items')
    with op.batch_alter_table('job_events', schema=None) as batch_op:
        batch_op.drop_index('ix_job_events_job_created')

    op.drop_table('job_events')
    with op.batch_alter_table('evidence_units', schema=None) as batch_op:
        batch_op.drop_index('ix_evidence_units_source_kind')
        batch_op.drop_index('ix_evidence_units_content_hash')

    op.drop_table('evidence_units')
    with op.batch_alter_table('entity_mentions', schema=None) as batch_op:
        batch_op.drop_index('ix_entity_mentions_source_run')
        batch_op.drop_index('ix_entity_mentions_resolved_entity_id')
        batch_op.drop_index('ix_entity_mentions_resolution_status')
        batch_op.drop_index('ix_entity_mentions_normalized_text')

    op.drop_table('entity_mentions')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index('ix_claims_subject_topic_predicate')
        batch_op.drop_index('ix_claims_subject_entity_predicate')
        batch_op.drop_index('ix_claims_source_id')
        batch_op.drop_index('ix_claims_processing_run_id')
        batch_op.drop_index('ix_claims_predicate')

    op.drop_table('claims')
    with op.batch_alter_table('wiki_pages', schema=None) as batch_op:
        batch_op.drop_index('ix_wiki_pages_topic_id')
        batch_op.drop_index('ix_wiki_pages_slug')
        batch_op.drop_index('ix_wiki_pages_page_type_status')
        batch_op.drop_index('ix_wiki_pages_entity_id')

    op.drop_table('wiki_pages')
    with op.batch_alter_table('source_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_source_snapshots_source_hash')
        batch_op.drop_index('ix_source_snapshots_source_fetched')

    op.drop_table('source_snapshots')
    op.drop_table('source_collection_memberships')
    with op.batch_alter_table('source_assets', schema=None) as batch_op:
        batch_op.drop_index('ix_source_assets_source_type')
        batch_op.drop_index('ix_source_assets_retention_expires')

    op.drop_table('source_assets')
    with op.batch_alter_table('processing_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_processing_runs_status')
        batch_op.drop_index('ix_processing_runs_source_started')

    op.drop_table('processing_runs')
    with op.batch_alter_table('processing_rules', schema=None) as batch_op:
        batch_op.drop_index('ix_processing_rules_target_source_id')
        batch_op.drop_index('ix_processing_rules_target_creator_id')
        batch_op.drop_index('ix_processing_rules_target_collection_id')
        batch_op.drop_index('ix_processing_rules_enabled_type')

    op.drop_table('processing_rules')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_type_status')
        batch_op.drop_index('ix_jobs_status_priority_available')
        batch_op.drop_index('ix_jobs_source_id')
        batch_op.drop_index('ix_jobs_locked_at_ms')

    op.drop_table('jobs')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index('ix_sources_source_type')
        batch_op.drop_index('ix_sources_saved_at_ms')
        batch_op.drop_index('ix_sources_creator_id')

    op.drop_table('sources')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_messages_conversation_created')

    op.drop_table('messages')
    with op.batch_alter_table('entity_user_states', schema=None) as batch_op:
        batch_op.drop_index('ix_entity_user_states_state')

    op.drop_table('entity_user_states')
    with op.batch_alter_table('entity_external_ids', schema=None) as batch_op:
        batch_op.drop_index('ix_entity_external_ids_entity_id')

    op.drop_table('entity_external_ids')
    with op.batch_alter_table('entity_aliases', schema=None) as batch_op:
        batch_op.drop_index('ix_entity_aliases_normalized_alias')

    op.drop_table('entity_aliases')
    op.drop_table('conversation_state')
    with op.batch_alter_table('vector_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_vector_documents_vector_key')

    op.drop_table('vector_documents')
    op.drop_table('topics')
    with op.batch_alter_table('search_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_search_documents_updated_at_ms')

    op.drop_table('search_documents')
    with op.batch_alter_table('quality_rules', schema=None) as batch_op:
        batch_op.drop_index('ix_quality_rules_status_finding_type')

    op.drop_table('quality_rules')
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index('ix_entities_type_normalized_name')
        batch_op.drop_index('ix_entities_status')

    op.drop_table('entities')
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.drop_index('ix_creators_platform_display_name')
        batch_op.drop_index('ix_creators_handle')

    op.drop_table('creators')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index('ix_conversations_updated_at_ms')

    op.drop_table('conversations')
    op.drop_table('collections')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
